# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e3b140a10966e5ccafb4fa38a171b47343c091013ebb3b4132cabafe38a8d17ba36690bdf594e10b5b3da76621e2cd07d7316da1958e08c14227aa019651bd6

test:
  secret_key_base: 453e278d80598090255f0bae13e529cc08f5ab95429d35e5745910b2c4de04e672371ff78fc6093c995c82f9b6990990980aee9fe1e908fee758971d3ae88312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
